### ISSUE TITLE
Unity demo shows ghost skeletons that are sitting still

### ISSUE THREAD

**Issue by joelpryde** [stimulant/MS-Cube-SDK#14]
During Unity experiments today, we’ve seen a few ghost skeletons sitting still, and some joints going Infinity or NaN or something, drawing crazy lines from origin and spewing error outputs.  I worked around that by disabling the GameObjects associated with the bodies of most of the “crazy” skeletons, like this at the top of RefreshBodyObject:
using System.Linq;
...
    private void RefreshBodyObject(KinectBody body, GameObject bodyObject)
    {
        bool hasBrokenJoint = (from joint in body.Joints
                               where float.IsInfinity(joint.x) || float.IsInfinity(joint.y) || float.IsInfinity(joint.z) ||
                                     float.IsNaN(joint.x) || float.IsNaN(joint.y) || float.IsNaN(joint.z)
                               select joint).Any();
        bool hasNonZeroPositioning = (from joint in body.Joints
                                      where joint.x != 0 || joint.y != 0 || joint.z != 0
                                      select joint).Any();
        if (hasBrokenJoint || !hasNonZeroPositioning)
        {
            bodyObject.SetActive(false);
            return;
        }
        bodyObject.SetActive(true);
       ...

However we suspect this should be unnecessary after some underlying issue with the SDK is found and fixed?

**Comment by joelpryde** [comment]
Believe I fixed this.  I fixed a bunch of errors with how the Unity Sample is processing data from Kinect Transport and am no longer seeing this.  Please re-open if you see it occur again!

**Comment by dr-ratio** [comment]
I don't see UI to reopen this, but after pulling latest, I am definitely still seeing ghost skeletons by walking off-screen and back on again.  Even after restarting Unity, then hitting Run, those old ghost skeletons come right back where they were stuck before.  May need to start a repro attempt by restarting KinectTransport before running the Unity demo.

**Comment by joelpryde** [comment]
Dang, reopening!

**Comment by joelpryde** [comment]
Finally tracked this down and fixed it (was an issue with KinectTransport).  You'll have to rebuild KinectTransport but you should not see anymore ghost skeletons.
